#!/usr/bin/env bash
BRANCH=$(git rev-parse --abbrev-ref HEAD)
# echo "Current branch: $BRANCH"
# if [[ "$BRANCH" == "main"  || "$BRANCH" == "develop" ]]; then
#   echo "Commit message should not be on $BRANCH branch"
#   exit 1
# fi

if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
    echo "Aborting commit. Your commit message is invalid." >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
    echo "Aborting commit. Your commit message is too long." >&2
    exit 1
fi